#!/usr/bin/env python3
"""
This tool does a rough analysis of the refresh rate for products produced by GCCS

Author: Nick Carrasco
Code generated by Google Gemini with Orchestration and cleanup by Nick Carrasco
"""

import argparse
import boto3
import pandas as pd
import re
import sys
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# --- CONFIGURATION ---
BUCKETS = ["gccs-products", "gccs-intermediate-products"]
DEFAULT_SATS = ["18", "19"]
MAX_WORKERS = 20  # Increased for folder-level parallelism
# ---------------------

def parse_args():
    parser = argparse.ArgumentParser(description="GOES-R Refresh Rate Metrics Reporter (Deep Parallel)")
    parser.add_argument("--sat", required=False, help="Satellite number. Default: 18 & 19.")
    parser.add_argument("--year", required=True, help="Year (e.g., 2026)")
    parser.add_argument("--doy", required=True, help="Day of Year (e.g., 058)")
    parser.add_argument("--level", required=False, choices=['L1b', 'L2'], help="Filter by L1b or L2")
    parser.add_argument("--output_file", required=False, help="Output CSV path")
    parser.add_argument("--quiet", action="store_true", help="Suppress all status messages")
    return parser.parse_args()

def analyze_goes_refresh(s3_objects):
    df = pd.DataFrame(s3_objects)
    if df.empty: return pd.DataFrame()

    df['Filename'] = df['Key'].str.split('/').str[-1]
    
    goes_regex = (
        r"^[A-Z0-9]+(?:_)?(?P<prefix>I_)?"
        r"(?P<sensor>[A-Z0-9]+)-"
        r"(?P<level>L1b|L2)-"
        r"(?P<product>[A-Z0-9]+?)"
        r"(?P<scene>F|C|M1|M2)?"
        r"(?:-(?P<mode>[A-Z0-9]+)?(?P<channel>C\d{2})?)?_"
        r"(?P<sat>G\d{2})_"
        r"s(?P<start>\d{14})_"
        r"e(?P<end>\d{14})_"
        r"c(?P<created>\d{14})"
    )
    
    extracted = df['Filename'].str.extract(goes_regex, flags=re.IGNORECASE)
    df = pd.concat([df, extracted], axis=1).dropna(subset=['start'])
    if df.empty: return pd.DataFrame()

    # Optimized ProductType generation to avoid double or trailing underscores
    def build_key(row):
        # Combine prefix and sensor into one element if prefix exists
        prefix_sensor = f"{row['prefix']}{row['sensor']}" if pd.notna(row['prefix']) else row['sensor']
        
        components = [
            prefix_sensor,
            row['level'],
            row['product'],
            row['scene'],
            row['mode'],
            row['channel'],
            row['sat']
        ]
        # Only join components that are not None, empty string, or NaN
        return "_".join([str(c) for c in components if pd.notna(c) and str(c).strip() != ""])

    df['ProductType'] = df.apply(build_key, axis=1)
    
    df['LastModified_dt'] = pd.to_datetime(df['LastModified'])
    df = df.sort_values(['ProductType', 'LastModified_dt'])
    df['delta'] = df.groupby('ProductType')['LastModified_dt'].diff().dt.total_seconds()

    return df.groupby('ProductType').agg(
        avg_delta_sec=('delta', 'mean'),
        min_delta_sec=('delta', 'min'),
        max_delta_sec=('delta', 'max'),
        file_count=('Filename', 'count'),
        first_start_time=('start', 'first')
    )

def get_subfolders(s3_client, bucket, prefix):
    subfolders = []
    paginator = s3_client.get_paginator('list_objects_v2')
    try:
        for page in paginator.paginate(Bucket=bucket, Prefix=prefix, Delimiter='/'):
            if 'CommonPrefixes' in page:
                subfolders.extend([p['Prefix'] for p in page['CommonPrefixes']])
    except Exception:
        pass 
    return subfolders

def scrape_folder_contents(bucket, path):
    """Worker function to list objects in a specific DOY folder."""
    session = boto3.Session(profile_name='geocloud')
    s3 = session.client('s3')
    paginator = s3.get_paginator('list_objects_v2')
    
    files = []
    try:
        for page in paginator.paginate(Bucket=bucket, Prefix=path):
            if 'Contents' in page:
                files.extend([
                    {'Key': o['Key'], 'LastModified': o['LastModified']} 
                    for o in page['Contents']
                ])
    except Exception:
        pass
    return files

def run_pipeline():
    args = parse_args()
    sats_to_check = [args.sat] if args.sat else DEFAULT_SATS
    session = boto3.Session(profile_name='geocloud')
    s3 = session.client('s3')
    
    # --- PHASE 1: DISCOVERY (Still relatively fast) ---
    if not args.quiet:
        print(f"--> Discovering product folders...")

    all_target_paths = [] # List of (bucket, path)
    for sat in sats_to_check:
        root_prefix = f"GCCS/op/GOES-{sat}/"
        for bucket in BUCKETS:
            levels = [f"{root_prefix}{args.level}/"] if args.level else get_subfolders(s3, bucket, root_prefix)
            instruments = []
            for l in levels:
                instruments.extend(get_subfolders(s3, bucket, l))
            for inst in instruments:
                for prod in get_subfolders(s3, bucket, inst):
                    # We check if the year/doy exists via a MaxKeys=1 check
                    doy_path = f"{prod}{args.year}/{args.doy}/"
                    all_target_paths.append((bucket, doy_path))

    # --- PHASE 2: DEEP PARALLEL SCRAPE ---
    if not args.quiet:
        print(f"--> Found {len(all_target_paths)} potential product folders.")
        print(f"--> Scraping file metadata using {MAX_WORKERS} threads...")

    all_files = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(scrape_folder_contents, b, p): (b, p) for b, p in all_target_paths}
        
        for future in as_completed(futures):
            res = future.result()
            if res:
                all_files.extend(res)

    # --- PHASE 3: ANALYSIS ---
    if not all_files:
        if not args.quiet: print("--> No data found.")
        return

    report = analyze_goes_refresh(all_files)

    if not report.empty:
        report = report.round(2)
        if args.output_file:
            report.to_csv(args.output_file)
            if not args.quiet: print(f"--> Success! Saved to {args.output_file}")

        if not args.quiet:
            print("\n" + "="*100 + f"\nREPORT | YEAR {args.year} | DOY {args.doy}\n" + "="*100)
        print(report.to_string())
        if not args.quiet: print("="*100)

if __name__ == "__main__":
    run_pipeline()